application: demo
version: 1
runtime: python
api_version: 1

handlers:
- url: /jstest
  script : jstest.py

- url: /cachetest
  script: cachetest.py

- url: /client
  script: client.py

- url: /status
  script: status.py

- url: /admin
  script: admin.py
  
- url: /settings
  script: settings.py

- url: /datastoreuploader
  script: datastoreuploader.py

- url : /testgearsdb
  script: testgearsdb.py
  
- url : /getdata
  script: getdata.py
  
- url : /dbquery
  script: dbquery.py

- url: /js
  static_dir: js

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /index
  script: index.py

- url : /.*
  script: index.py

