application: demo
version: 1
runtime: python
api_version: 1

handlers:
- url: /jstest
  script : jstest.py

- url: /cachetest
  script: cachetest.py

- url: /js
  static_dir: js

- url : /.*
  script: index.py

